Update tutorial 7 and related code
ATOMScience-org/AMPL pull request #287
Opened 2024-04-17 00:17 UTC by paulsonak

Update tutorial 7 and related code
1. Update explanations and expand function calls so that people see all the options
2. clean up tutorial by proofreading and removing importlib calls from when I was developing
3. Update new code for multitask model comparisons by making the column names the same between different compare_models functions
4. Update plotting code to count colors correctly, and not create a regression plot for a classification model

2024-05-01 22:35 UTC, mwtorres requested changes
@paulsonak Tutorial7 and the pipeline module changes look good. I wasn't able to test the Adhoc6 multitask tutorial. Could you add more description of which Adhoc tutorials to run in preparation or save a multitask model in the tutorial dataset as input?

2024-05-01 23:08 UTC, stewarthe6 approved these changes

2024-05-01 23:10 UTC, stewarthe6 commented
I think the ad hoc tutorials are more of a place holder right now and aren't meant to be rigorous. They're also out of order, the numbers aren't meaningful.

2024-05-16 20:36 UTC, merged

2024-05-16 20:37 UTC, mauvais2 commented
Defer the change request for later release. Thanks.